module boundary
  use interface_boundary
  use point_to_boundary_generic
  use point_to_boundary_test_6
  use point_to_boundary_test_7
  use point_to_boundary_test_8
  use point_to_boundary_test_9
  use point_to_boundary_test_10
  use point_to_boundary_test_11
  use point_to_boundary_test_12
  use point_to_boundary_test_13
  use point_to_boundary_test_14
  use point_to_boundary_test_15
  use point_to_boundary_test_16
  use point_to_boundary_test_17
  use point_to_boundary_test_18
  use point_to_boundary_test_21
  use point_to_boundary_test_22
  use point_to_boundary_test_23
  use point_to_boundary_test_24
  use point_to_boundary_test_25
  use point_to_boundary_test_26
  use point_to_boundary_test_27
  use point_to_boundary_test_28
  use point_to_boundary_test_29
  use point_to_boundary_test_30
  use point_to_boundary_test_31
  use point_to_boundary_test_32
  use point_to_boundary_test_33
  use point_to_boundary_test_34
  use point_to_boundary_test_35
  use point_to_boundary_test_36
  use point_to_boundary_test_37
  use point_to_boundary_test_38
  use point_to_boundary_test_39
  use point_to_boundary_test_40
  
CONTAINS
  SUBROUTINE assign_boundary
    USE input_data
    USE my_util
    IMPLICIT NONE
    INTEGER :: i
    IF (inputs%test_de_convergence) THEN
       i=inputs%numero_du_test_debug
    ELSE
       i=0
    END IF
    SELECT case(i)
    case(0) 
       init_velocity_pressure => init_velocity_pressure_generic
       init_temperature => init_temperature_generic
       init_level_set =>  init_level_set_generic
       source_in_NS_momentum =>  source_in_NS_momentum_generic
       source_in_temperature =>  source_in_temperature_generic
       source_in_level_set =>  source_in_level_set_generic
       vv_exact =>  vv_exact_generic
       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_generic
       pp_exact =>  pp_exact_generic
       temperature_exact=>  temperature_exact_generic 
       level_set_exact =>  level_set_exact_generic
       penal_in_real_space =>  penal_in_real_space_generic 
       extension_velocity =>  extension_velocity_generic
       Vexact =>  Vexact_generic
       H_B_quasi_static =>  H_B_quasi_static_generic
       Hexact =>  Hexact_generic
       Phiexact =>  Phiexact_generic 
       Jexact_gauss =>  Jexact_gauss_generic
       Eexact_gauss =>  Eexact_gauss_generic
       init_maxwell =>  init_maxwell_generic
       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_generic
       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_generic 
       mu_in_real_space=>  mu_in_real_space_generic
       sigma_bar_in_fourier_space =>  sigma_bar_in_fourier_space_generic
       chi_coeff_law => chi_coeff_law_generic
       T_dchi_dT_coeff_law => T_dchi_dT_coeff_law_generic
       nu_tilde_law => nu_tilde_law_generic
    case(6) 
!!$       init_velocity_pressure => init_velocity_pressure_test_6
!!$       init_temperature => init_temperature_test_6
!!$       init_level_set =>  init_level_set_test_6
!!$       source_in_NS_momentum =>  source_in_NS_momentum_test_6
!!$       source_in_temperature =>  source_in_temperature_test_6
!!$       source_in_level_set =>  source_in_level_set_test_6
!!$       vv_exact =>  vv_exact_test_6
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_6
!!$       pp_exact =>  pp_exact_test_6
!!$       temperature_exact=>  temperature_exact_test_6 
!!$       level_set_exact =>  level_set_exact_test_6
!!$       penal_in_real_space =>  penal_in_real_space_test_6 
!!$       extension_velocity =>  extension_velocity_test_6
       Vexact =>  Vexact_test_6
!!$       H_B_quasi_static =>  H_B_quasi_static_test_6
       Hexact =>  Hexact_test_6
       Phiexact =>  Phiexact_test_6 
       Jexact_gauss =>  Jexact_gauss_test_6
       Eexact_gauss =>  Eexact_gauss_test_6
       init_maxwell =>  init_maxwell_test_6
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_6
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_6 
!!$       mu_in_real_space=>  mu_in_real_space_test_6 
    case(7) 
!!$       init_velocity_pressure => init_velocity_pressure_test_7
!!$       init_temperature => init_temperature_test_7
!!$       init_level_set =>  init_level_set_test_7
!!$       source_in_NS_momentum =>  source_in_NS_momentum_test_7
!!$       source_in_temperature =>  source_in_temperature_test_7
!!$       source_in_level_set =>  source_in_level_set_test_7
!!$       vv_exact =>  vv_exact_test_7
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_7
!!$       pp_exact =>  pp_exact_test_7
!!$       temperature_exact=>  temperature_exact_test_7 
!!$       level_set_exact =>  level_set_exact_test_7
!!$       penal_in_real_space =>  penal_in_real_space_test_7 
!!$       extension_velocity =>  extension_velocity_test_7
       Vexact =>  Vexact_test_7
!!$       H_B_quasi_static =>  H_B_quasi_static_test_7
       Hexact =>  Hexact_test_7
       Phiexact =>  Phiexact_test_7 
       Jexact_gauss =>  Jexact_gauss_test_7
       Eexact_gauss =>  Eexact_gauss_test_7
       init_maxwell =>  init_maxwell_test_7
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_7
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_7 
!!$       mu_in_real_space=>  mu_in_real_space_test_7 
    case(8) 
       init_velocity_pressure => init_velocity_pressure_test_8
       init_temperature => init_temperature_test_8
!!$       init_level_set =>  init_level_set_test_8
       source_in_NS_momentum =>  source_in_NS_momentum_test_8
       source_in_temperature =>  source_in_temperature_test_8
!!$       source_in_level_set =>  source_in_level_set_test_8
       vv_exact =>  vv_exact_test_8
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_8
       pp_exact =>  pp_exact_test_8
       temperature_exact=>  temperature_exact_test_8 
!!$       level_set_exact =>  level_set_exact_test_8
!!$       penal_in_real_space =>  penal_in_real_space_test_8 
       extension_velocity =>  extension_velocity_test_8
!!$       Vexact =>  Vexact_test_8
!!$       H_B_quasi_static =>  H_B_quasi_static_test_8
!!$       Hexact =>  Hexact_test_8
!!$       Phiexact =>  Phiexact_test_8 
!!$       Jexact_gauss =>  Jexact_gauss_test_8
!!$       Eexact_gauss =>  Eexact_gauss_test_8
!!$       init_maxwell =>  init_maxwell_test_8
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_8
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_8 
!!$       mu_in_real_space=>  mu_in_real_space_test_8 
    case(9) 
       init_velocity_pressure => init_velocity_pressure_test_9
       init_temperature => init_temperature_test_9
!!$       init_level_set =>  init_level_set_test_9
       source_in_NS_momentum =>  source_in_NS_momentum_test_9
       source_in_temperature =>  source_in_temperature_test_9
!!$       source_in_level_set =>  source_in_level_set_test_9
       vv_exact =>  vv_exact_test_9
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_9
       pp_exact =>  pp_exact_test_9
       temperature_exact=>  temperature_exact_test_9 
!!$       level_set_exact =>  level_set_exact_test_9
!!$       penal_in_real_space =>  penal_in_real_space_test_9 
       extension_velocity =>  extension_velocity_test_9
!!$       Vexact =>  Vexact_test_9
!!$       H_B_quasi_static =>  H_B_quasi_static_test_9
!!$       Hexact =>  Hexact_test_9
!!$       Phiexact =>  Phiexact_test_9 
!!$       Jexact_gauss =>  Jexact_gauss_test_9
!!$       Eexact_gauss =>  Eexact_gauss_test_9
!!$       init_maxwell =>  init_maxwell_test_9
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_9
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_9 
!!$       mu_in_real_space=>  mu_in_real_space_test_9 
    case(10) 
!!$       init_velocity_pressure => init_velocity_pressure_test_10
!!$       init_temperature => init_temperature_test_10
!!$       init_level_set =>  init_level_set_test_10
!!$       source_in_NS_momentum =>  source_in_NS_momentum_test_10
!!$       source_in_temperature =>  source_in_temperature_test_10
!!$       source_in_level_set =>  source_in_level_set_test_10
!!$       vv_exact =>  vv_exact_test_10
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_10
!!$       pp_exact =>  pp_exact_test_10
!!$       temperature_exact=>  temperature_exact_test_10 
!!$       level_set_exact =>  level_set_exact_test_10
!!$       penal_in_real_space =>  penal_in_real_space_test_10 
!!$       extension_velocity =>  extension_velocity_test_10
       Vexact =>  Vexact_test_10
!!$       H_B_quasi_static =>  H_B_quasi_static_test_10
       Hexact =>  Hexact_test_10
       Phiexact =>  Phiexact_test_10 
       Jexact_gauss =>  Jexact_gauss_test_10
       Eexact_gauss =>  Eexact_gauss_test_10
       init_maxwell =>  init_maxwell_test_10
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_10
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_10 
!!$       mu_in_real_space=>  mu_in_real_space_test_10 
    case(11) 
       init_velocity_pressure => init_velocity_pressure_test_11
       init_temperature => init_temperature_test_11
!!$       init_level_set =>  init_level_set_test_11
       source_in_NS_momentum =>  source_in_NS_momentum_test_11
       source_in_temperature =>  source_in_temperature_test_11
!!$       source_in_level_set =>  source_in_level_set_test_11
       vv_exact =>  vv_exact_test_11
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_11
       pp_exact =>  pp_exact_test_11
       temperature_exact=>  temperature_exact_test_11 
!!$       level_set_exact =>  level_set_exact_test_11
!!$       penal_in_real_space =>  penal_in_real_space_test_11 
       extension_velocity =>  extension_velocity_test_11
!!$       Vexact =>  Vexact_test_11
!!$       H_B_quasi_static =>  H_B_quasi_static_test_11
       Hexact =>  Hexact_test_11
       Phiexact =>  Phiexact_test_11 
       Jexact_gauss =>  Jexact_gauss_test_11
       Eexact_gauss =>  Eexact_gauss_test_11
       init_maxwell =>  init_maxwell_test_11
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_11
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_11 
!!$       mu_in_real_space=>  mu_in_real_space_test_11 
    case(12) 
!!$       init_velocity_pressure => init_velocity_pressure_test_12
!!$       init_temperature => init_temperature_test_12
!!$       init_level_set =>  init_level_set_test_12
!!$       source_in_NS_momentum =>  source_in_NS_momentum_test_12
!!$       source_in_temperature =>  source_in_temperature_test_12
!!$       source_in_level_set =>  source_in_level_set_test_12
!!$       vv_exact =>  vv_exact_test_12
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_12
!!$       pp_exact =>  pp_exact_test_12
!!$       temperature_exact=>  temperature_exact_test_12 
!!$       level_set_exact =>  level_set_exact_test_12
!!$       penal_in_real_space =>  penal_in_real_space_test_12 
!!$       extension_velocity =>  extension_velocity_test_12
       Vexact =>  Vexact_test_12
!!$       H_B_quasi_static =>  H_B_quasi_static_test_12
       Hexact =>  Hexact_test_12
       Phiexact =>  Phiexact_test_12 
       Jexact_gauss =>  Jexact_gauss_test_12
       Eexact_gauss =>  Eexact_gauss_test_12
       init_maxwell =>  init_maxwell_test_12
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_12
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_12 
!!$       mu_in_real_space=>  mu_in_real_space_test_12 
    case(13) 
       init_velocity_pressure => init_velocity_pressure_test_13
!!$       init_temperature => init_temperature_test_13
!!$       init_level_set =>  init_level_set_test_13
       source_in_NS_momentum =>  source_in_NS_momentum_test_13
!!$       source_in_temperature =>  source_in_temperature_test_13
!!$       source_in_level_set =>  source_in_level_set_test_13
       vv_exact =>  vv_exact_test_13
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_13
       pp_exact =>  pp_exact_test_13
!!$       temperature_exact=>  temperature_exact_test_13 
!!$       level_set_exact =>  level_set_exact_test_13
!!$       penal_in_real_space =>  penal_in_real_space_test_13 
       extension_velocity =>  extension_velocity_test_13
!!$       Vexact =>  Vexact_test_13
!!$       H_B_quasi_static =>  H_B_quasi_static_test_13
       Hexact =>  Hexact_test_13
       Phiexact =>  Phiexact_test_13 
       Jexact_gauss =>  Jexact_gauss_test_13
       Eexact_gauss =>  Eexact_gauss_test_13
       init_maxwell =>  init_maxwell_test_13
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_13
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_13 
!!$       mu_in_real_space=>  mu_in_real_space_test_13 
    case(14) 
!!$       init_velocity_pressure => init_velocity_pressure_test_14
!!$       init_temperature => init_temperature_test_14
!!$       init_level_set =>  init_level_set_test_14
!!$       source_in_NS_momentum =>  source_in_NS_momentum_test_14
!!$       source_in_temperature =>  source_in_temperature_test_14
!!$       source_in_level_set =>  source_in_level_set_test_14
!!$       vv_exact =>  vv_exact_test_14
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_14
!!$       pp_exact =>  pp_exact_test_14
!!$       temperature_exact=>  temperature_exact_test_14 
!!$       level_set_exact =>  level_set_exact_test_14
!!$       penal_in_real_space =>  penal_in_real_space_test_14 
!!$       extension_velocity =>  extension_velocity_test_14
       Vexact =>  Vexact_test_14
!!$       H_B_quasi_static =>  H_B_quasi_static_test_14
       Hexact =>  Hexact_test_14
       Phiexact =>  Phiexact_test_14 
       Jexact_gauss =>  Jexact_gauss_test_14
       Eexact_gauss =>  Eexact_gauss_test_14
       init_maxwell =>  init_maxwell_test_14
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_14
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_14 
!!$       mu_in_real_space=>  mu_in_real_space_test_14 
    case(15) 
       init_velocity_pressure => init_velocity_pressure_test_15
       init_temperature => init_temperature_test_15
!!$       init_level_set =>  init_level_set_test_15
       source_in_NS_momentum =>  source_in_NS_momentum_test_15
       source_in_temperature =>  source_in_temperature_test_15
!!$       source_in_level_set =>  source_in_level_set_test_15
       vv_exact =>  vv_exact_test_15
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_15
       pp_exact =>  pp_exact_test_15
       temperature_exact=>  temperature_exact_test_15 
!!$       level_set_exact =>  level_set_exact_test_15
!!$       penal_in_real_space =>  penal_in_real_space_test_15 
       extension_velocity =>  extension_velocity_test_15
!!$       Vexact =>  Vexact_test_15
!!$       H_B_quasi_static =>  H_B_quasi_static_test_15
!!$       Hexact =>  Hexact_test_15
!!$       Phiexact =>  Phiexact_test_15 
!!$       Jexact_gauss =>  Jexact_gauss_test_15
!!$       Eexact_gauss =>  Eexact_gauss_test_15
!!$       init_maxwell =>  init_maxwell_test_15
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_15
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_15 
!!$       mu_in_real_space=>  mu_in_real_space_test_15 
    case(16) 
       init_velocity_pressure => init_velocity_pressure_test_16
!!$       init_temperature => init_temperature_test_16
!!$       init_level_set =>  init_level_set_test_16
       source_in_NS_momentum =>  source_in_NS_momentum_test_16
!!$       source_in_temperature =>  source_in_temperature_test_16
!!$       source_in_level_set =>  source_in_level_set_test_16
       vv_exact =>  vv_exact_test_16
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_16
       pp_exact =>  pp_exact_test_16
!!$       temperature_exact=>  temperature_exact_test_16 
!!$       level_set_exact =>  level_set_exact_test_16
!!$       penal_in_real_space =>  penal_in_real_space_test_16 
!!$       extension_velocity =>  extension_velocity_test_16
!!$       Vexact =>  Vexact_test_16
!!$       H_B_quasi_static =>  H_B_quasi_static_test_16
!!$       Hexact =>  Hexact_test_16
!!$       Phiexact =>  Phiexact_test_16 
!!$       Jexact_gauss =>  Jexact_gauss_test_16
!!$       Eexact_gauss =>  Eexact_gauss_test_16
!!$       init_maxwell =>  init_maxwell_test_16
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_16
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_16 
!!$       mu_in_real_space=>  mu_in_real_space_test_16 
    case(17) 
!!$       init_velocity_pressure => init_velocity_pressure_test_17
!!$       init_temperature => init_temperature_test_17
!!$       init_level_set =>  init_level_set_test_17
!!$       source_in_NS_momentum =>  source_in_NS_momentum_test_17
!!$       source_in_temperature =>  source_in_temperature_test_17
!!$       source_in_level_set =>  source_in_level_set_test_17
!!$       vv_exact =>  vv_exact_test_17
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_17
!!$       pp_exact =>  pp_exact_test_17
!!$       temperature_exact=>  temperature_exact_test_17 
!!$       level_set_exact =>  level_set_exact_test_17
!!$       penal_in_real_space =>  penal_in_real_space_test_17 
!!$       extension_velocity =>  extension_velocity_test_17
       Vexact =>  Vexact_test_17
!!$       H_B_quasi_static =>  H_B_quasi_static_test_17
       Hexact =>  Hexact_test_17
       Phiexact =>  Phiexact_test_17 
       Jexact_gauss =>  Jexact_gauss_test_17
       Eexact_gauss =>  Eexact_gauss_test_17
       init_maxwell =>  init_maxwell_test_17
       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_17
       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_17 
!!$       mu_in_real_space=>  mu_in_real_space_test_17 
    case(18) 
!!$       init_velocity_pressure => init_velocity_pressure_test_18
!!$       init_temperature => init_temperature_test_18
!!$       init_level_set =>  init_level_set_test_18
!!$       source_in_NS_momentum =>  source_in_NS_momentum_test_18
!!$       source_in_temperature =>  source_in_temperature_test_18
!!$       source_in_level_set =>  source_in_level_set_test_18
!!$       vv_exact =>  vv_exact_test_18
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_18
!!$       pp_exact =>  pp_exact_test_18
!!$       temperature_exact=>  temperature_exact_test_18 
!!$       level_set_exact =>  level_set_exact_test_18
!!$       penal_in_real_space =>  penal_in_real_space_test_18 
!!$       extension_velocity =>  extension_velocity_test_18
       Vexact =>  Vexact_test_18
!!$       H_B_quasi_static =>  H_B_quasi_static_test_18
       Hexact =>  Hexact_test_18
       Phiexact =>  Phiexact_test_18 
       Jexact_gauss =>  Jexact_gauss_test_18
       Eexact_gauss =>  Eexact_gauss_test_18
       init_maxwell =>  init_maxwell_test_18
       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_18
       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_18 
!!$       mu_in_real_space=>  mu_in_real_space_test_18 
    case(21) 
       init_velocity_pressure => init_velocity_pressure_test_21
!!$       init_temperature => init_temperature_test_21
       init_level_set =>  init_level_set_test_21
       source_in_NS_momentum =>  source_in_NS_momentum_test_21
!!$       source_in_temperature =>  source_in_temperature_test_21
       source_in_level_set =>  source_in_level_set_test_21
       vv_exact =>  vv_exact_test_21
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_21
       pp_exact =>  pp_exact_test_21
!!$       temperature_exact=>  temperature_exact_test_21 
       level_set_exact =>  level_set_exact_test_21
!!$       penal_in_real_space =>  penal_in_real_space_test_21 
       extension_velocity =>  extension_velocity_test_21
!!$       Vexact =>  Vexact_test_21
!!$       H_B_quasi_static =>  H_B_quasi_static_test_21
       Hexact =>  Hexact_test_21
       Phiexact =>  Phiexact_test_21 
       Jexact_gauss =>  Jexact_gauss_test_21
       Eexact_gauss =>  Eexact_gauss_test_21
       init_maxwell =>  init_maxwell_test_21
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_21
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_21 
!!$       mu_in_real_space=>  mu_in_real_space_test_21
       sigma_bar_in_fourier_space =>  sigma_bar_in_fourier_space_21
    case(22) 
!!$       init_velocity_pressure => init_velocity_pressure_test_22
!!$       init_temperature => init_temperature_test_22
!!$       init_level_set =>  init_level_set_test_22
!!$       source_in_NS_momentum =>  source_in_NS_momentum_test_22
!!$       source_in_temperature =>  source_in_temperature_test_22
!!$       source_in_level_set =>  source_in_level_set_test_22
!!$       vv_exact =>  vv_exact_test_22
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_22
!!$       pp_exact =>  pp_exact_test_22
!!$       temperature_exact=>  temperature_exact_test_22 
!!$       level_set_exact =>  level_set_exact_test_22
!!$       penal_in_real_space =>  penal_in_real_space_test_22 
!!$       extension_velocity =>  extension_velocity_test_22
       Vexact =>  Vexact_test_22
!!$       H_B_quasi_static =>  H_B_quasi_static_test_22
       Hexact =>  Hexact_test_22
       Phiexact =>  Phiexact_test_22 
       Jexact_gauss =>  Jexact_gauss_test_22
       Eexact_gauss =>  Eexact_gauss_test_22
       init_maxwell =>  init_maxwell_test_22
       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_22
       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_22 
       mu_in_real_space=>  mu_in_real_space_test_22 
    case(23) 
!!$       init_velocity_pressure => init_velocity_pressure_test_23
!!$       init_temperature => init_temperature_test_23
!!$       init_level_set =>  init_level_set_test_23
!!$       source_in_NS_momentum =>  source_in_NS_momentum_test_23
!!$       source_in_temperature =>  source_in_temperature_test_23
!!$       source_in_level_set =>  source_in_level_set_test_23
!!$       vv_exact =>  vv_exact_test_23
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_23
!!$       pp_exact =>  pp_exact_test_23
!!$       temperature_exact=>  temperature_exact_test_23 
!!$       level_set_exact =>  level_set_exact_test_23
!!$       penal_in_real_space =>  penal_in_real_space_test_23 
!!$       extension_velocity =>  extension_velocity_test_23
       Vexact =>  Vexact_test_23
!!$       H_B_quasi_static =>  H_B_quasi_static_test_23
       Hexact =>  Hexact_test_23
       Phiexact =>  Phiexact_test_23 
       Jexact_gauss =>  Jexact_gauss_test_23
       Eexact_gauss =>  Eexact_gauss_test_23
       init_maxwell =>  init_maxwell_test_23
       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_23
       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_23 
       mu_in_real_space=>  mu_in_real_space_test_23 
    case(24) 
       init_velocity_pressure => init_velocity_pressure_test_24
!!$       init_temperature => init_temperature_test_24
!!$       init_level_set =>  init_level_set_test_24
       source_in_NS_momentum =>  source_in_NS_momentum_test_24
!!$       source_in_temperature =>  source_in_temperature_test_24
!!$       source_in_level_set =>  source_in_level_set_test_24
       vv_exact =>  vv_exact_test_24
       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_24
       pp_exact =>  pp_exact_test_24
!!$       temperature_exact=>  temperature_exact_test_24 
!!$       level_set_exact =>  level_set_exact_test_24
       penal_in_real_space =>  penal_in_real_space_test_24 
!!$       extension_velocity =>  extension_velocity_test_24
!!$       Vexact =>  Vexact_test_24
!!$       H_B_quasi_static =>  H_B_quasi_static_test_24
!!$       Hexact =>  Hexact_test_24
!!$       Phiexact =>  Phiexact_test_24 
!!$       Jexact_gauss =>  Jexact_gauss_test_24
!!$       Eexact_gauss =>  Eexact_gauss_test_24
!!$       init_maxwell =>  init_maxwell_test_24
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_24
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_24 
!!$       mu_in_real_space=>  mu_in_real_space_test_24 
    case(25) 
       init_velocity_pressure => init_velocity_pressure_test_25
!!$       init_temperature => init_temperature_test_25
       init_level_set =>  init_level_set_test_25
       source_in_NS_momentum =>  source_in_NS_momentum_test_25
!!$       source_in_temperature =>  source_in_temperature_test_25
       source_in_level_set =>  source_in_level_set_test_25
       vv_exact =>  vv_exact_test_25
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_25
       pp_exact =>  pp_exact_test_25
!!$       temperature_exact=>  temperature_exact_test_25 
       level_set_exact =>  level_set_exact_test_25
!!$       penal_in_real_space =>  penal_in_real_space_test_25 
!!$       extension_velocity =>  extension_velocity_test_25
!!$       Vexact =>  Vexact_test_25
!!$       H_B_quasi_static =>  H_B_quasi_static_test_25
!!$       Hexact =>  Hexact_test_25
!!$       Phiexact =>  Phiexact_test_25 
!!$       Jexact_gauss =>  Jexact_gauss_test_25
!!$       Eexact_gauss =>  Eexact_gauss_test_25
!!$       init_maxwell =>  init_maxwell_test_25
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_25
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_25 
!!$       mu_in_real_space=>  mu_in_real_space_test_25 
    case(26) 
!!$       init_velocity_pressure => init_velocity_pressure_test_26
!!$       init_temperature => init_temperature_test_26
!!$       init_level_set =>  init_level_set_test_26
!!$       source_in_NS_momentum =>  source_in_NS_momentum_test_26
!!$       source_in_temperature =>  source_in_temperature_test_26
!!$       source_in_level_set =>  source_in_level_set_test_26
!!$       vv_exact =>  vv_exact_test_26
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_26
!!$       pp_exact =>  pp_exact_test_26
!!$       temperature_exact=>  temperature_exact_test_26 
!!$       level_set_exact =>  level_set_exact_test_26
!!$       penal_in_real_space =>  penal_in_real_space_test_26 
!!$       extension_velocity =>  extension_velocity_test_26
       Vexact =>  Vexact_test_26
!!$       H_B_quasi_static =>  H_B_quasi_static_test_26
       Hexact =>  Hexact_test_26
       Phiexact =>  Phiexact_test_26 
       Jexact_gauss =>  Jexact_gauss_test_26
       Eexact_gauss =>  Eexact_gauss_test_26
       init_maxwell =>  init_maxwell_test_26
       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_26
       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_26 
!!$       mu_in_real_space=>  mu_in_real_space_test_26 
    case(27) 
!!$       init_velocity_pressure => init_velocity_pressure_test_27
!!$       init_temperature => init_temperature_test_27
!!$       init_level_set =>  init_level_set_test_27
!!$       source_in_NS_momentum =>  source_in_NS_momentum_test_27
!!$       source_in_temperature =>  source_in_temperature_test_27
!!$       source_in_level_set =>  source_in_level_set_test_27
!!$       vv_exact =>  vv_exact_test_27
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_27
!!$       pp_exact =>  pp_exact_test_27
!!$       temperature_exact=>  temperature_exact_test_27 
!!$       level_set_exact =>  level_set_exact_test_27
!!$       penal_in_real_space =>  penal_in_real_space_test_27 
!!$       extension_velocity =>  extension_velocity_test_27
       Vexact =>  Vexact_test_27
!!$       H_B_quasi_static =>  H_B_quasi_static_test_27
       Hexact =>  Hexact_test_27
       Phiexact =>  Phiexact_test_27 
       Jexact_gauss =>  Jexact_gauss_test_27
       Eexact_gauss =>  Eexact_gauss_test_27
       init_maxwell =>  init_maxwell_test_27
       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_27
       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_27 
       mu_in_real_space=>  mu_in_real_space_test_27 
    case(28) 
       init_velocity_pressure => init_velocity_pressure_test_28
!!$       init_temperature => init_temperature_test_28
!!$       init_level_set =>  init_level_set_test_28
       source_in_NS_momentum =>  source_in_NS_momentum_test_28
!!$       source_in_temperature =>  source_in_temperature_test_28
!!$       source_in_level_set =>  source_in_level_set_test_28
       vv_exact =>  vv_exact_test_28
       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_28
       pp_exact =>  pp_exact_test_28
!!$       temperature_exact=>  temperature_exact_test_28 
!!$       level_set_exact =>  level_set_exact_test_28
       penal_in_real_space =>  penal_in_real_space_test_28 
!!$       extension_velocity =>  extension_velocity_test_28
!!$       Vexact =>  Vexact_test_28
!!$       H_B_quasi_static =>  H_B_quasi_static_test_28
!!$       Hexact =>  Hexact_test_28
!!$       Phiexact =>  Phiexact_test_28 
!!$       Jexact_gauss =>  Jexact_gauss_test_28
!!$       Eexact_gauss =>  Eexact_gauss_test_28
!!$       init_maxwell =>  init_maxwell_test_28
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_28
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_28 
!!$       mu_in_real_space=>  mu_in_real_space_test_28 
    case(29) 
       init_velocity_pressure => init_velocity_pressure_test_29
!!$       init_temperature => init_temperature_test_29
!!$       init_level_set =>  init_level_set_test_29
       source_in_NS_momentum =>  source_in_NS_momentum_test_29
!!$       source_in_temperature =>  source_in_temperature_test_29
!!$       source_in_level_set =>  source_in_level_set_test_29
       vv_exact =>  vv_exact_test_29
       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_29
       pp_exact =>  pp_exact_test_29
!!$       temperature_exact=>  temperature_exact_test_29 
!!$       level_set_exact =>  level_set_exact_test_29
       penal_in_real_space =>  penal_in_real_space_test_29 
       extension_velocity =>  extension_velocity_test_29
!!$       Vexact =>  Vexact_test_29
!!$       H_B_quasi_static =>  H_B_quasi_static_test_29
       Hexact =>  Hexact_test_29
       Phiexact =>  Phiexact_test_29 
       Jexact_gauss =>  Jexact_gauss_test_29
       Eexact_gauss =>  Eexact_gauss_test_29
       init_maxwell =>  init_maxwell_test_29
       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_29
       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_29 
       mu_in_real_space=>  mu_in_real_space_test_29 
    case(30) 
       init_velocity_pressure => init_velocity_pressure_test_30
       init_temperature => init_temperature_test_30
!!$       init_level_set =>  init_level_set_test_30
       source_in_NS_momentum =>  source_in_NS_momentum_test_30
       source_in_temperature =>  source_in_temperature_test_30
!!$       source_in_level_set =>  source_in_level_set_test_30
       vv_exact =>  vv_exact_test_30
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_30
       pp_exact =>  pp_exact_test_30
       temperature_exact=>  temperature_exact_test_30 
!!$       level_set_exact =>  level_set_exact_test_30
!!$       penal_in_real_space =>  penal_in_real_space_test_30 
       extension_velocity =>  extension_velocity_test_30
!!$       Vexact =>  Vexact_test_30
!!$       H_B_quasi_static =>  H_B_quasi_static_test_30
!!$       Hexact =>  Hexact_test_30
!!$       Phiexact =>  Phiexact_test_30 
!!$       Jexact_gauss =>  Jexact_gauss_test_30
!!$       Eexact_gauss =>  Eexact_gauss_test_30
!!$       init_maxwell =>  init_maxwell_test_30
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_30
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_30 
!!$       mu_in_real_space=>  mu_in_real_space_test_30 
    case(31) 
       init_velocity_pressure => init_velocity_pressure_test_31
       init_temperature => init_temperature_test_31
!!$       init_level_set =>  init_level_set_test_31
       source_in_NS_momentum =>  source_in_NS_momentum_test_31
       source_in_temperature =>  source_in_temperature_test_31
!!$       source_in_level_set =>  source_in_level_set_test_31
       vv_exact =>  vv_exact_test_31
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_31
       pp_exact =>  pp_exact_test_31
       temperature_exact=>  temperature_exact_test_31 
!!$       level_set_exact =>  level_set_exact_test_31
!!$       penal_in_real_space =>  penal_in_real_space_test_31 
       extension_velocity =>  extension_velocity_test_31
!!$       Vexact =>  Vexact_test_31
!!$       H_B_quasi_static =>  H_B_quasi_static_test_31
!!$       Hexact =>  Hexact_test_31
!!$       Phiexact =>  Phiexact_test_31 
!!$       Jexact_gauss =>  Jexact_gauss_test_31
!!$       Eexact_gauss =>  Eexact_gauss_test_31
!!$       init_maxwell =>  init_maxwell_test_31
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_31
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_31 
!!$       mu_in_real_space=>  mu_in_real_space_test_31 
    case(32) 
       init_velocity_pressure => init_velocity_pressure_test_32
       init_temperature => init_temperature_test_32
!!$       init_level_set =>  init_level_set_test_32
       source_in_NS_momentum =>  source_in_NS_momentum_test_32
       source_in_temperature =>  source_in_temperature_test_32
!!$       source_in_level_set =>  source_in_level_set_test_32
       vv_exact =>  vv_exact_test_32
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_32
       pp_exact =>  pp_exact_test_32
       temperature_exact=>  temperature_exact_test_32 
!!$       level_set_exact =>  level_set_exact_test_32
!!$       penal_in_real_space =>  penal_in_real_space_test_32 
       extension_velocity =>  extension_velocity_test_32
!!$       Vexact =>  Vexact_test_32
!!$       H_B_quasi_static =>  H_B_quasi_static_test_32
!!$       Hexact =>  Hexact_test_32
!!$       Phiexact =>  Phiexact_test_32 
!!$       Jexact_gauss =>  Jexact_gauss_test_32
!!$       Eexact_gauss =>  Eexact_gauss_test_32
!!$       init_maxwell =>  init_maxwell_test_32
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_32
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_32 
!!$       mu_in_real_space=>  mu_in_real_space_test_32 
    case(33)
       init_velocity_pressure => init_velocity_pressure_test_33
       init_temperature => init_temperature_test_33
!!$       init_level_set =>  init_level_set_test_33
       source_in_NS_momentum =>  source_in_NS_momentum_test_33
       source_in_temperature =>  source_in_temperature_test_33
!!$       source_in_level_set =>  source_in_level_set_test_33
       vv_exact =>  vv_exact_test_33
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_33
       pp_exact =>  pp_exact_test_33
       temperature_exact=>  temperature_exact_test_33 
!!$       level_set_exact =>  level_set_exact_test_33
!!$       penal_in_real_space =>  penal_in_real_space_test_33 
       extension_velocity =>  extension_velocity_test_33
!!$       Vexact =>  Vexact_test_33
!!$       H_B_quasi_static =>  H_B_quasi_static_test_33
       Hexact =>  Hexact_test_33
       Phiexact =>  Phiexact_test_33 
       Jexact_gauss =>  Jexact_gauss_test_33
       Eexact_gauss =>  Eexact_gauss_test_33
       init_maxwell =>  init_maxwell_test_33
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_33
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_33 
!!$       mu_in_real_space=>  mu_in_real_space_test_33
       chi_coeff_law => chi_coeff_law_test_33
       T_dchi_dT_coeff_law => T_dchi_dT_coeff_law_test_33
    case(34)
       init_velocity_pressure => init_velocity_pressure_test_34
       init_temperature => init_temperature_test_34
!!$       init_level_set =>  init_level_set_test_34
       source_in_NS_momentum =>  source_in_NS_momentum_test_34
       source_in_temperature =>  source_in_temperature_test_34
!!$       source_in_level_set =>  source_in_level_set_test_34
       vv_exact =>  vv_exact_test_34
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_34
       pp_exact =>  pp_exact_test_34
       temperature_exact=>  temperature_exact_test_34 
!!$       level_set_exact =>  level_set_exact_test_34
!!$       penal_in_real_space =>  penal_in_real_space_test_34 
       extension_velocity =>  extension_velocity_test_34
!!$       Vexact =>  Vexact_test_34
!!$       H_B_quasi_static =>  H_B_quasi_static_test_34
       Hexact =>  Hexact_test_34
       Phiexact =>  Phiexact_test_34 
       Jexact_gauss =>  Jexact_gauss_test_34
       Eexact_gauss =>  Eexact_gauss_test_34
       init_maxwell =>  init_maxwell_test_34
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_34
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_34 
!!$       mu_in_real_space=>  mu_in_real_space_test_34
       chi_coeff_law => chi_coeff_law_test_34
       T_dchi_dT_coeff_law => T_dchi_dT_coeff_law_test_34
    case(35) 
       init_velocity_pressure => init_velocity_pressure_test_35
       init_temperature => init_temperature_test_35
!!$       init_level_set =>  init_level_set_test_35
       source_in_NS_momentum =>  source_in_NS_momentum_test_35
       source_in_temperature =>  source_in_temperature_test_35
!!$       source_in_level_set =>  source_in_level_set_test_35
       vv_exact =>  vv_exact_test_35
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_35
       pp_exact =>  pp_exact_test_35
       temperature_exact=>  temperature_exact_test_35 
!!$       level_set_exact =>  level_set_exact_test_35
!!$       penal_in_real_space =>  penal_in_real_space_test_35 
       extension_velocity =>  extension_velocity_test_35
!!$       Vexact =>  Vexact_test_35
!!$       H_B_quasi_static =>  H_B_quasi_static_test_35
!!$       Hexact =>  Hexact_test_35
!!$       Phiexact =>  Phiexact_test_35 
!!$       Jexact_gauss =>  Jexact_gauss_test_35
!!$       Eexact_gauss =>  Eexact_gauss_test_35
!!$       init_maxwell =>  init_maxwell_test_35
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_35
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_35 
!!$       mu_in_real_space=>  mu_in_real_space_test_35 
    case(36) 
       init_velocity_pressure => init_velocity_pressure_test_36
       init_temperature => init_temperature_test_36
 !!$       init_level_set =>  init_level_set_test_36
      source_in_NS_momentum =>  source_in_NS_momentum_test_36
       source_in_temperature =>  source_in_temperature_test_36
!!$       source_in_level_set =>  source_in_level_set_test_36
       vv_exact =>  vv_exact_test_36
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_36
       pp_exact =>  pp_exact_test_36
       temperature_exact=>  temperature_exact_test_36 
!!$       level_set_exact =>  level_set_exact_test_36
!!$       penal_in_real_space =>  penal_in_real_space_test_36 
       extension_velocity =>  extension_velocity_test_36
!!$       Vexact =>  Vexact_test_36
!!$       H_B_quasi_static =>  H_B_quasi_static_test_36
!!$       Hexact =>  Hexact_test_36
!!$       Phiexact =>  Phiexact_test_36 
!!$       Jexact_gauss =>  Jexact_gauss_test_36
!!$       Eexact_gauss =>  Eexact_gauss_test_36
!!$       init_maxwell =>  init_maxwell_test_36
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_36
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_36 
!!$       mu_in_real_space=>  mu_in_real_space_test_36 
       nu_tilde_law => nu_tilde_law_test_36
    case(37)
       init_velocity_pressure => init_velocity_pressure_test_37
       init_temperature => init_temperature_test_37
!!$       init_level_set =>  init_level_set_test_37
       source_in_NS_momentum =>  source_in_NS_momentum_test_37
       source_in_temperature =>  source_in_temperature_test_37
!!$       source_in_level_set =>  source_in_level_set_test_37
       vv_exact =>  vv_exact_test_37
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_37
       pp_exact =>  pp_exact_test_37
       temperature_exact=>  temperature_exact_test_37 
!!$       level_set_exact =>  level_set_exact_test_37
!!$       penal_in_real_space =>  penal_in_real_space_test_37 
       extension_velocity =>  extension_velocity_test_37
!!$       Vexact =>  Vexact_test_37
!!$       H_B_quasi_static =>  H_B_quasi_static_test_37
       Hexact =>  Hexact_test_37
       Phiexact =>  Phiexact_test_37 
       Jexact_gauss =>  Jexact_gauss_test_37
       Eexact_gauss =>  Eexact_gauss_test_37
       init_maxwell =>  init_maxwell_test_37
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_37
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_37 
!!$       mu_in_real_space=>  mu_in_real_space_test_37
       chi_coeff_law => chi_coeff_law_test_37
       T_dchi_dT_coeff_law => T_dchi_dT_coeff_law_test_37
    case(38)
       init_velocity_pressure => init_velocity_pressure_test_38
       init_temperature => init_temperature_test_38
!!$       init_level_set =>  init_level_set_test_38
       source_in_NS_momentum =>  source_in_NS_momentum_test_38
       source_in_temperature =>  source_in_temperature_test_38
!!$       source_in_level_set =>  source_in_level_set_test_38
       vv_exact =>  vv_exact_test_38
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_38
       pp_exact =>  pp_exact_test_38
       temperature_exact=>  temperature_exact_test_38 
!!$       level_set_exact =>  level_set_exact_test_38
!!$       penal_in_real_space =>  penal_in_real_space_test_38 
       extension_velocity =>  extension_velocity_test_38
!!$       Vexact =>  Vexact_test_38
!!$       H_B_quasi_static =>  H_B_quasi_static_test_38
       Hexact =>  Hexact_test_38
       Phiexact =>  Phiexact_test_38 
       Jexact_gauss =>  Jexact_gauss_test_38
       Eexact_gauss =>  Eexact_gauss_test_38
       init_maxwell =>  init_maxwell_test_38
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_38
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_38 
!!$       mu_in_real_space=>  mu_in_real_space_test_38
       chi_coeff_law => chi_coeff_law_test_38
       T_dchi_dT_coeff_law => T_dchi_dT_coeff_law_test_38
      case(39) 
       init_velocity_pressure => init_velocity_pressure_test_39
!!$       init_temperature => init_temperature_test_39
       init_level_set =>  init_level_set_test_39
       source_in_NS_momentum =>  source_in_NS_momentum_test_39
!!$       source_in_temperature =>  source_in_temperature_test_39
       source_in_level_set =>  source_in_level_set_test_39
       vv_exact =>  vv_exact_test_39
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_39
       pp_exact =>  pp_exact_test_39
!!$       temperature_exact=>  temperature_exact_test_39 
       level_set_exact =>  level_set_exact_test_39
!!$       penal_in_real_space =>  penal_in_real_space_test_39 
!!$       extension_velocity =>  extension_velocity_test_39
!!$       Vexact =>  Vexact_test_39
!!$       H_B_quasi_static =>  H_B_quasi_static_test_39
!!$       Hexact =>  Hexact_test_39
!!$       Phiexact =>  Phiexact_test_39 
!!$       Jexact_gauss =>  Jexact_gauss_test_39
!!$       Eexact_gauss =>  Eexact_gauss_test_39
!!$       init_maxwell =>  init_maxwell_test_39
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_39
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_39 
!!$       mu_in_real_space=>  mu_in_real_space_test_39 
    case(40) 
       init_velocity_pressure => init_velocity_pressure_test_40
!!$       init_temperature => init_temperature_test_40
       init_level_set =>  init_level_set_test_40
       source_in_NS_momentum =>  source_in_NS_momentum_test_40
!!$       source_in_temperature =>  source_in_temperature_test_40
       source_in_level_set =>  source_in_level_set_test_40
       vv_exact =>  vv_exact_test_40
!!$       imposed_velocity_by_penalty =>  imposed_velocity_by_penalty_test_40
       pp_exact =>  pp_exact_test_40
!!$       temperature_exact=>  temperature_exact_test_40 
       level_set_exact =>  level_set_exact_test_40
!!$       penal_in_real_space =>  penal_in_real_space_test_40 
!!$       extension_velocity =>  extension_velocity_test_40
!!$       Vexact =>  Vexact_test_40
!!$       H_B_quasi_static =>  H_B_quasi_static_test_40
!!$       Hexact =>  Hexact_test_40
!!$       Phiexact =>  Phiexact_test_40 
!!$       Jexact_gauss =>  Jexact_gauss_test_40
!!$       Eexact_gauss =>  Eexact_gauss_test_40
!!$       init_maxwell =>  init_maxwell_test_40
!!$       mu_bar_in_fourier_space =>  mu_bar_in_fourier_space_test_40
!!$       grad_mu_bar_in_fourier_space=>  grad_mu_bar_in_fourier_space_test_40 
!!$       mu_in_real_space=>  mu_in_real_space_test_40

    CASE DEFAULT
       CALL error_petsc(' BUG in assign_boundary, wrong test number')
    end SELECT
  END SUBROUTINE assign_boundary
end module boundary
