#!/bin/bash

iter_beg=19
iter_end=20

#Set local environment variables
export MY_MPIRUN="mpirun -np"
##################################################################


##################################################################
#Definition of SFEMaNS_TEST_DIR
export SFEMaNS_TEST_DIR=$1/MHD_DATA_TEST_CONV_PETSC
export SFEMaNS_DIR=$1
echo $SFEMaNS_DIR
echo $SFEMaNS_TEST_DIR

#Check status of files
echo '' > lis

if (( iter_beg==20 )); then
   iter_beg=19
fi

if (( iter_beg==32 )); then
   iter_beg=31
fi

for iter in $(seq $iter_beg $iter_end)
do

if (( iter == 14)) # Excludes 14 
then
  continue      # Skip rest of this particular loop iteration.
fi

    
if [ -f fort.57 ]; then
   rm fort.57
fi
if [ -f fort.10 ]; then
   rm fort.10
fi

#Start tests
echo 'Starting test '$iter

datatest=$SFEMaNS_TEST_DIR/debug_data_$iter
echo $datatest
ok_ns=0
ok_nf=0
ns=1
nf=1
while read line 
do
   if (( ok_ns == 1 )); then
      ns=$line
      ok_ns=0
   fi
   if (( ok_nf == 1 )); then
      nf=$line
      ok_nf=0
   fi
   if [ "$line" == "===Number of processors in meridian section" ]; then
      ok_ns=1
   fi
   if [ "$line" == "===Number of processors in Fourier space" ]; then
      ok_nf=1
   fi
done < $datatest
nproc=$(( ns*nf ))

if (( iter == 20 )); then #iter = 20 is a special case 
    cp ${SFEMaNS_DIR}/MESH_INTERPOLATION/mesh_interpolation .
    cp $SFEMaNS_TEST_DIR/Mesh_10_form.FEM .
    cp $SFEMaNS_TEST_DIR/Mesh_20_form.FEM .
    cp suite_ns_S000_I001.Mesh_10_form.FEM suite_ns_S000_I002.Mesh_10_form.FEM 
    cp $SFEMaNS_TEST_DIR/debug_data_19_interpol data_interpol
    ./mesh_interpolation $3
    for FILE in suite_*I002*; do mv "$FILE" $(echo "$FILE" | sed 's/_I002//'); done
fi

if (( iter == 32 )); then #iter = 32 is a special case 
    cd INTERPOLATION_MESH
    cp ${SFEMaNS_DIR}/MESH_INTERPOLATION/mesh_interpolation .
    cp $SFEMaNS_TEST_DIR/SOLID_FLUID_10.FEM .
    cp $SFEMaNS_TEST_DIR/SOLID_FLUID_20.FEM .
    cp ../suite_ns_S000_I001.SOLID_FLUID_10.FEM .
    cp ../suite_temp_S000_I001.SOLID_FLUID_10.FEM .
    cp ../mesh_part_S1.SOLID_FLUID_10.FEM .
    cp $SFEMaNS_TEST_DIR/debug_data_31_interpol data_interpol
    ./mesh_interpolation
    for FILE in suite_*; do mv "$FILE" $(echo "$FILE" | sed 's/_I001//'); done
    mv suite* ..
    mv mesh_part_S5.SOLID_FLUID_20.FEM ..
    cd ..
fi

$MY_MPIRUN $nproc ./$2 debug $iter debug_dir $SFEMaNS_TEST_DIR  >> lis 2>&1
    
testok=$( grep 'Reading failure' lis | tail -n 1 )
if [ "$testok" == " Reading failure" ]; then
   echo $testok
   exit
else
   if [ -f fort.57 ] ; then
      cat fort.57
      mv fort.10 fort.10_T$iter
   else
      echo 'Test failure'
      nerr=$(( nproc + 1 ))
      tail -n $nerr lis | head -n 1
   fi
fi

done

